matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "6"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  yarn: true

install:
  - yarn install

script:
  - yarn run build
  - yarn run pack
  - zip -r release.zip release -q

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

addons:
  artifacts:
    s3_region: us-east-1
    paths: release.zip
    debug: true
