version: 0.4.{build}

environment:
  matrix:
    - nodejs_version: 8
      POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

platform:
  - x64

services:
  - postgresql96

cache:
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%


install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install --force

build_script:
  - yarn run build
  - yarn run pack

after_build:
  - cd release && 7z a win-release.zip *.exe

artifacts:
  - path: release\win-release.zip

test: off
