version: 0.4.{build}

environment:
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6

platform:
  - x64

services:
  - postgresql96

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%


install:
  - ps: Install-Product node 7 x64
  - npm install
  - npm install electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - npm run package

after_build:
  - 7z a release.zip release

artifacts:
  - path: release.zip
    name: release

test: off
