version: 0.4.{build}

platform:
  - x64

services:
  - postgresql  # or postgresql96

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
	- ps: $env:PATH+=";C:\Program Files\PostgreSQL\9.2\bin"
  - npm install
  - npm install electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - npm run package

test: off
