version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
      - image: quay.io/plotly/falcon-test-spark
      - image: quay.io/plotly/falcon-test-db2
    environment:
      PATH: "/usr/local/opt/curl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/circleci/project/node_modules/.bin"
      PLOTLY_CONNECTOR_IS_RUNNING_ON_CIRCLE_CI: "true"
    working_directory: /home/circleci/falcon
    steps:
      - restore_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          keys:
            - v1-source-{{ .Branch }}-
            - v1-source-
      - checkout
      - save_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - restore_cache:
          key: v1-yarn-{{ checksum "package.json" }}
          keys:
            - v1-yarn-
      - run: yarn install
      - run: yarn run rebuild:modules:electron
      - save_cache:
          key: v1-yarn-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn run build
      - run: yarn run test
      - run: yarn run pack
      - run: mkdir artifacts
      - run: mv release/*.yml artifacts || true
      - run: mv release/falcon-sql-client* artifacts
      - store_artifacts:
          path: artifacts
