mysql:
    username: masteruser
    password: connecttoplotly
    database: null
    port: 3306
    dialect: mysql
    storage: null
    host: readonly-test-mysql.cwwxgcilxwxw.us-west-2.rds.amazonaws.com
mariadb:
    username: masteruser
    password: connecttoplotly
    database: null
    port: 3306
    dialect: mariadb
    storage: null
    host: readonly-test-mariadb.cwwxgcilxwxw.us-west-2.rds.amazonaws.com
mssql:
    username: masteruser
    password: connecttoplotly
    database: null
    port: 1433
    dialect: mssql
    storage: null
    host: test-mysql.cwwxgcilxwxw.us-west-2.rds.amazonaws.com
postgres:
    username: masteruser
    password: connecttoplotly
    database: plotly_database
    port: 5432
    dialect: postgres
    storage: null
    host: readonly-test-postgres.cwwxgcilxwxw.us-west-2.rds.amazonaws.com
elasticsearch:
    username: null
    password: null
    database: null
    port: 9200
    dialect: elasticsearch
    storage: null
    host: http://67a7441549120daa2dbeef8ac4f5bb2e.us-east-1.aws.found.io
